### ISSUE TITLE
Error on page: Summary - Section 1

### ISSUE THREAD

**Issue by ghost** [KiranWells/web-app#5]
**Describe the Error**
Which page is the error on? Which problem?
Change of Basis

**Explain the answer**
If you can, explain what the text should say.
"u = V * (U^(-1)) * v" -> u = (U^(-1)) * V * v

**Additional context**
U-1 = 3x3
V= 3x1
inside numbers need to match for matrices 
V*U-1 != U-1*V
3x1 * 3x3 != 3x3 * 3x1

**Comment by KiranWells** [comment]
Thank you for the error report.

This is an error, but not because of the dimensions. Both V and U are square matrices, and v and u are the coordinates in their corresponding bases; the error is because the coordinates should be transformed by V *first* and then by U<sup>-1</sup>. I will try to make that clearer on the page.
